# Use root/example as user/password credentials
version: '3.1'
networks:
  qzkraft-net:
    external: true
services:
  mongo:
    image: "mongo:7.0"
    container_name: mongo-qzkraft-net
    restart: always    
    ports:
      - 27017:27017
    networks:
      - qzkraft-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
    volumes:
      - mongodb-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
  redis:
    image: "redis:7-alpine"
    command: redis-server --requirepass ${REDIS_kEY}
    container_name: redis-qzkraft-net
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
     - qzkraft-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
volumes:
  mongodb-data: