# Use root/example as user/password credentials
version: '3.1'
networks:
  qzkraft-net:
    external: true
services:
  mongo:
    image: "mongo:7.0"
    container_name: mongo-qzkraft-ctr
    restart: always    
    ports:
      - 8037:27017
    networks:
      - qzkraft-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
    volumes:
      - mongodb-data:/data/db
  redis:
    image: "redis:7-alpine"
    command: redis-server --requirepass ${REDIS_kEY}
    container_name: redis-qzkraft-ctr
    ports:
     - "8039:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
     - qzkraft-net
volumes:
  mongodb-data:
